# DISPLAY
DISPLAY_WIDTH = 700
DISPLAY_HEIGHT = 700

# GRID
GRID_SIZE = (10, 10)
DRAW_GRID = False
RECT_SIZE = (DISPLAY_WIDTH // GRID_SIZE[0], DISPLAY_HEIGHT // GRID_SIZE[1])

# COLORS
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
DARK_ORANGE = (255, 140, 0)
SNAKE_HEAD_COLOR = RED
SNAKE_TAIL_COLOR = WHITE
GRID_BORDER_COLOR = DARK_ORANGE
SNAKE_SENSOR_COLOR = (0, 51, 0)

# APPLE
APPLE_COLOR = GREEN
APPLE_EXTRA_MOVES = 100

# FPS
FPS = 30

# SNAKE
MOVES = 100

# POINTS FOR FITNESS
POINTS_FOR_COLLISION = 0
POINTS_FOR_NEAR_APPLE = 1
POINTS_FOR_AWAY_APPLE = -2
APPLE_POINTS = 1

# GENETIC ALGORITHM
NUMBER_OF_POPULATION = 200
NUMBER_OF_GENERATION = 200
NUMBER_PARENTS_CROSSOVER = 10
MUTATION_PERCENTAGE = 0.1
NUMBER_OF_GAMES_PER_CHROMOSOME = 1

# NEURAL NETWORK
INPUT = 10
NEURONS_HIDDEN_1 = 6
OUTPUT = 4
NUMBER_WEIGHTS = INPUT * NEURONS_HIDDEN_1 + NEURONS_HIDDEN_1 * OUTPUT

# GENERATION FILES
GENERATION_FILES_FOLDER = 'generations_files/'
LAST_GENERATION_FILE_NAME = GENERATION_FILES_FOLDER + 'latest_generation_number.csv'
WEIGHTS_FILES_FOLDER = GENERATION_FILES_FOLDER + 'weights/'
SCORES_FILES_FOLDER = GENERATION_FILES_FOLDER + 'scores/'
BEST_SCORER_FOLDER = GENERATION_FILES_FOLDER + 'best_scorer/'
