# DISPLAY
DISPLAY_WIDTH = 700
DISPLAY_HEIGHT = 700

# GRID
GRID_SIZE = (20, 20)
DRAW_GRID = False
RECT_SIZE = (DISPLAY_WIDTH // GRID_SIZE[0], DISPLAY_HEIGHT // GRID_SIZE[1])

# COLORS
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
DARK_ORANGE = (255, 140, 0)
SNAKE_HEAD_COLOR = RED
SNAKE_TAIL_COLOR = WHITE
GRID_BORDER_COLOR = DARK_ORANGE
APPLE_COLOR = GREEN

# APPLE
APPLE_EXTRA_MOVES = 100

# FPS
FPS = 60

# SNAKE
PIECE_FOR_APPLE = 1
MOVES = 100
MAX_MOVES = 500

# POINTS FOR FITNESS
APPLE_POINTS = 1

# GENETIC ALGORITHM
NUMBER_OF_POPULATION = 200
NUMBER_OF_GENERATION = 200
NUMBER_PARENTS_CROSSOVER = 10
MUTATION_PERCENTAGE = 0.1

# NEURAL NETWORK
INPUT = 10
NEURONS_HIDDEN_1 = 6
OUTPUT = 3
NUMBER_WEIGHTS = INPUT * NEURONS_HIDDEN_1 + NEURONS_HIDDEN_1 * OUTPUT

# GENERATION FILES
GENERATION_FILES_FOLDER = 'generations_files/'
LAST_GENERATION_FILE_NAME = GENERATION_FILES_FOLDER + 'latest_generation_number.csv'
WEIGHTS_FILES_FOLDER = GENERATION_FILES_FOLDER + 'weights/'
SCORES_FILES_FOLDER = GENERATION_FILES_FOLDER + 'scores/'
BEST_SCORER_FOLDER = GENERATION_FILES_FOLDER + 'best_scorer/'
